//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxyGame.EntityFrameworkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolarSystem
    {
        public SolarSystem()
        {
            this.SpaceObjects = new HashSet<SpaceObject>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid GalaxyId { get; set; }
    
        public virtual Galaxy Galaxy { get; set; }
        public virtual ICollection<SpaceObject> SpaceObjects { get; set; }
    }
}
