//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxyGame.EntityFrameworkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSystem
    {
        public SubSystem()
        {
            this.SpaceObjects = new HashSet<SpaceObject>();
            this.SubSystems1 = new HashSet<SubSystem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> SubSystemId { get; set; }
    
        public virtual ICollection<SpaceObject> SpaceObjects { get; set; }
        public virtual ICollection<SubSystem> SubSystems1 { get; set; }
        public virtual SubSystem SubSystem1 { get; set; }
    }
}
